name: Build and publish docker image

on:
  push:
    branches:
      - master

# Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    name: Builds the image and publishes to docker hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: mosmo321/github-actions-delete-abandoned-branches:v3
